### ISSUE TITLE
Don't "pre-remove" the JAR compression

### ISSUE THREAD

**Issue by eyalroz** [cleidigh/EditEmailSubject-MX#1]
A lot of extensions use JAR, for various reasons. Perhaps they're all invalid, perhaps not.

If JARs are completely unsupported in MailExtensions - fine, lets remove them, but the removal is part of the process which should be elucidated in this repository. So I suggest the initial commit(s) and release be overwritten to have the JAR still.

**Comment by cleidigh** [comment]
@eyalroz 
I did two things 
I have the original as is in src-original
I also maintained the original with the jar as the first commit
I only removed it after that because it makes everything easier.  
I was going to documented with a mettaissue

**Comment by eyalroz** [comment]
That's good. But... removing the JAR should be a regular issue ("task"-labeled?) which should be filed, then the action taken - so that we can keep track and so that commits relate to issues (hopefully every commit relates to an issue).

**Comment by cleidigh** [comment]
@eyalroz 
Do you know where the documentation is for thick covers using jar approach?
we could reference that and perhaps also find the answer  to your question if MX
extensions will ever use that paradigm.  I don't know the answer but I would guess not
only because of the double compression , but to be honest since I've never used it
perhaps I'm missing something.

**Comment by neandr** [comment]
The original XPI has a JAR and the install.rdf has <em:unpack>true</em:unpack>
So everything is OK with it.
Please refer also to [unpackingXPI](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/4/Updating_extensions_for_Firefox_4#XPI_unpacking) which says it's not necessary to pack a JAR nowadays.
For our project it's not an issue, so going to close it.
