### ISSUE TITLE
What can I do with donation money ?

### ISSUE THREAD

**Issue by jisse44** [cleidigh/EditEmailSubject-MX#14]
Hi all,

As I said before, I don't have enough time to devote to this project right now.

But this add-on seems  to be  awaited by a large number of users, and they donate via the link on the AMO site.
Right now I have 60€ on my Paypal account, which I don't want if I don't do dev myself.

Do you have any idea what to do with it or who to redistribute these funds to?

Thanks

**Comment by eyalroz** [comment]
A few options:

1. Donate it to the Thunderbird project, [here](https://give.thunderbird.net/en-US/?utm_source=thunderbird.net&utm_medium=referral&utm_content=header). The money is needed.
2. Donate it to authors of other extensions which you use and like.
3. Donate it to the Yemeni people. They are currently under a blockade by Saudi Arabia due to the, well, something between a civil war and a Saudi-US onslaught, depends on how you look at it. Millions of people are malnourished or hungry, the medical system has broken down, it's horrible. [Oxfam](https://www.oxfam.org.au/what-we-do/emergencies/learn-about-current-emergencies/yemen-crisis/) is one place to donate, but there's actually a [list of organizations](https://www.pri.org/stories/2017-11-29/heres-how-you-can-send-help-people-trapped-worlds-worst-humanitarian-crisis) involved in humanitarian relief there, and you can see what each of them does and choose which you find fitting.
4. Speaking of civilians suffering due to war, the Syrian civil-and-proxy war is still ongoing - now in it's 10th year. But even in regions where there isn't currently fighting, there's incredible devastation, mass displacement and abject poverty of people whose entire lives have folded like a deck of cards and carried by the wings of violence - and now live in camps, or sometimes in places abandoned by inhabitants who themselves have ended up elsewhere. Now, donations for Syrians are a bit tricky, because western powers have been rather supportive of the Isalmist fundamentalists, who are quite brutal and mostly foreign elements; while the government side is itself oppressive and may not be too trustworthy when it comes to aid disbursement. I think the [ICRC](https://www.icrc.org/en/document/life-syria) should be a pretty safe choice, they run refugee camps in several places.

**Comment by jobisoft** [comment]
@jisse44 : We are about to release the version updated to ATN. Are you allowing us to upload it under your old add-on?

https://addons.thunderbird.net/de/thunderbird/addon/edit-email-subject/

You just have to reply "yes" in this issue, the ATN admin will then add one of us as Developers to your add-on and we can upload it.

This is the best solution for your users, as they get the update automatically.

**Comment by jisse44** [comment]
Hello

Waw, you dis such great work 

Yes of course you can release the version.

**Comment by jobisoft** [comment]
Thanks @jisse44 . I just talked to the admin and he suggested, that if you are still "around", that you add me by yourself, as thery do not want to (miss-)use their admin power if not needed, which is a good thing actually.

All you have to do is login here to ATN:

https://addons.thunderbird.net/en-US/thunderbird/

by clicking on "log in" in the upper right corner and than open this page

https://addons.thunderbird.net/en-US/developers/addon/edit-email-subject/ownership

where you can add me as a developer (my email is john.bieling@gmx.de). Here you can see how it looks like for quicktext, where I am one of the owners:

![grafik](https://user-images.githubusercontent.com/5830621/77250673-da5a8800-6c49-11ea-9cdb-96eb39e2d558.png)


Adding me will make me a developer, not an owner, which is enough to be able to upload new versions.

**Comment by jisse44** [comment]
ok it's done

**Comment by jobisoft** [comment]
Thanks!
