### ISSUE TITLE
Preferences: Current system description/capabilities WIP

### ISSUE THREAD

**Issue by cleidigh** [cleidigh/EditEmailSubject-MX#16]
Basic overview for comparison discussion:

Documentation: (more?)

https://developer.mozilla.org/en-US/docs/Mozilla/Preferences/Preferences_system
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefBranch

Capabilities Overview:
- handles default/startup values (storage : file system, nsiFile, pref.js)
- Methods : get/set individual preferences by type, preference change listeners, lock, Delete...
- Preference handling within xul, HTML (substitution, auto set)
- Open access to core prefs & cross Add-on preferences
- Preferences maintained after uninstall
- Preference elements and styles for common preference management pages
- Preference save / load buttons? (could be from a legacy library)

**Comment by neandr** [comment]
Not to forget Standard8 post about handling legacy prefs / localStorge .. how migrate
https://github.com/thundernest/sample-extensions/tree/master/legacyPrefMigration

**Comment by RealRaven2000** [comment]
**Use Cases**

Tb Core preference access. Read, Write!
Examples: 
- Switch for showing mail tabs in Caption Bar (Windows specific)
- Read current locale
- Default text direction
- Imap manual override for filtering mail into another folder (by moving mail back)

**Cross - Add-on Preference Access**
- Add-ons that are multi-components should be allowed to share preferences info somehow. They are usually by the same author
- Plugins for Add-ons. how to "open up" prefs between 2 owners.
- Two Add-ons with no relationship for sharing preferences. What will be allowed?

**Life-Cycle**
- Application Upgrades / Method changes. If the preferences have to migrated to a new system or back to an old one. (Who should be responsible to implement this, App or Add-on?)
- Defaults: Installation will set _default prefs_
- Persistence: Restarting thunderbird or disabling an Add-on: prefs remain persistent
- Reset: an action to reset should be available, reasonable assumption is uninstall resets all settings
- preference maintenance on uninstall: backup / restore (import / export) ... these should be discoverable for the average user (and maybe suggested on uninstall)
- Sync: synchronization across profiles / machines (synced local storage?) needs to be granular, e.g. categories such as layout/profile/account specific

**Events**
- Uninstall Event (Add-on MUST be notified)
- Install Event
- Update Event (to  show change log / monetisation etc.)
- Reset (should this be something Core offers?)
- Preference Modification Events by the User / UI 

**Types**
- primitives (bool / int / string)
- structured data (e.g. json)
- "blob"

**Comment by Standard8** [comment]
>     * Switch for showing mail tabs in Caption Bar (Windows specific)

That should be an API. Then it doesn't matter how the back-end is implemented and TB can either handle updates directly, or set the preference, but if the back-end wants to change it isn't locked into managing a pref.

>     * Read current locale

`browser.i18n` already [gives access to this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n).

>     * Default text direction

Presumably this is for display of html. If so, you can do this via css:

```
body {
   direction: __MSG_@@bidi_dir__;
}
```

You could probably use `browser.i18n.getMessage("__MSG_@@bidi_dir__")` as well for javascript, but I'm not 100% sure. There looks to be other ways of managing it.

Also xref https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Internationalization#Predefined_messages

>     * Imap manual override for filtering mail into another folder (by moving mail back)

This definitely sounds like it should be an API, for the same reason as the first one above.

> **Cross - Add-on Preference Access**
> 
>     * Add-ons that are multi-components should be allowed to share preferences info somehow. They are usually by the same author
>     * Plugins for Add-ons. how to "open up" prefs between 2 owners.
>     * Two Add-ons with no relationship for sharing preferences. What will be allowed?

You can provide a specific interface between extensions via messaging: https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage

That would not only give preference access, but mean you'd get notified of changes directly, rather than having to do extra work to watch prefs, and, of course, it isn't limited to just prefs. 

> **Life-Cycle**
> 
>     * Application Upgrades / Method changes. If the preferences have to migrated to a new system or back to an old one. (Who should be responsible to implement this, App or Add-on?)

`browser.storage` already guarantees this.

>     * Defaults: Installation will set _default prefs_

This is so trivial I think it isn't needed. You can easily default with things like `value = (await browser.storage.local.get("blah") || foo)`. Though you can also make things easy for yourself and initialise all prefs with a default value when you first start up.

>     * Persistence: Restarting thunderbird or disabling an Add-on: prefs remain persistent

WebExtensions do this already.

>     * Reset: an action to reset should be available, reasonable assumption is uninstall resets all settings

I think this is an add-on's responsibility to provide. Thunderbird shouldn't have to know how to reset your data.

>     * preference maintenance on uninstall: backup / restore (import / export) ... these should be discoverable for the average user (and maybe suggested on uninstall)

I generally disagree with this case, but if we're really going for it, I'd suggest maybe prompting users on uninstall.

>     * Sync: synchronization across profiles / machines (synced local storage?) needs to be granular, e.g. categories such as layout/profile/account specific

`browser.storage.sync` will do this if Thunderbird sets up sync. The other files depends - I'd suggest looking at what is available on Firefox there.

> **Events**
> 
>     * Uninstall Event (Add-on MUST be notified)

This might not be possible, for example an add-on has been disabled. I suspect there may be other cases, but both Chrome and Firefox don't have a notification for this. You might want to ask those add-on teams for the reason. There is an uninstall URL option: `https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/setUninstallURL`

>     * Install Event
>     * Update Event (to  show change log / monetisation etc.)

For both: `browser.runtime.onInstalled.addListener`

>     * Reset (should this be something Core offers?)

*Shrug* Most add-ons aren't that complex.

>     * Preference Modification Events by the User / UI

You can track changes to `browser.storage`

> **Types**
> 
>     * primitives (bool / int / string)

`browser.storage` supports any type like this that you want to save.
> 
>     * structured data (e.g. json)

You can even store an object into `browser.storage` as long as it is serialisable, and you don't have to worry about `JSON.parse` etc.

>     * "blob"

If you can make this into a string, that can easily be stored, or you could store this in IndexedDB according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Working_with_files#Store_files_data_locally_using_the_IndexedDB_file_storage_library

> **User Interface**
> 
>     * what components / styles should be supported. (XUL - HTML5 transition)
>     * UI standards, what OS styles will be removed? "-moz-appearance"

I'm not sure what this is trying to reference. The preferences page has html5 capability, and allows authors to lay things out as they want, and handle preferences as they want, e.g. Conversations' are handled with React.

I think there is a possibility for a browser supplied style sheet, but I couldn't get that to work when I tried it previously xref https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui#Syntax

Personally I wouldn't want constructs other than standard HTML, though some styles would be useful.

**Comment by jobisoft** [comment]
> - Preferences maintained after uninstall

Besides `browser.storage.local`, there is also `browser.storage.sync` which is used by Firefox Sync for data that should be synced with a Firefox account. If the user has not setup Firefox Sync, this data is of course not synced. To mimick the behaviour of synced data, it is currently not removed on add-on removal and can be reused upon add-on reinstall.

Even though Thunderbird does not offer to setup a Firefox Sync account, that API is still available and can be used as descibed.

However, the behaviour is different from `chrome.storage.sync` (which Firefox usually follows). Chrome clears the sync storage.

I know you will hate me for this, but I think, having a clear standing on a subject is better than relying on bug, which could be fixed anytime. I therefore raised awareness of this and they have already created a bug for it.

https://bugzilla.mozilla.org/show_bug.cgi?id=1618860

However, if you read the comments, this does not seem to be a clear case at all. We will have to wait and see.

A possible alternative solution is to automatically dump user data (via download API) on a regular basis and allow the user to import these dumps on re-install. I will evaluate that further.

**Comment by jobisoft** [comment]
Just to gather all the information at one point, the following core settings might also be intersting:
```
extensions.webextensions.keepStorageOnUninstall
extensions.webextensions.keepUuidOnUninstall
```

If both set to true, the standard local storage is not reset. I would however not advice you to manipulate those. This basically shows, why WebExtensions Experiments (with which you could flip those without telling the user) are considerred dangerous.

**Comment by RealRaven2000** [comment]
> Just to gather all the information at one point, the following core settings might also be intersting:
> 
> ```
> extensions.webextensions.keepStorageOnUninstall
> extensions.webextensions.keepUuidOnUninstall
> ```
thanks at first glance, that looks good. What's `keepUuidOnUninstall` ?

Ideally this should be per extension - changing this as a global setting wouldn't be something I would want to; most extensions do not need this but the real time saver / productivity / highly UI customizing ones (quickText? QuickFolders!) that have lots of settings / user provided setup shouldn't just be nuked on uninstall. 

But I guess I will have to go with experiment for this round anyway because so many functions will not be available as APIs. 

[_It may even have to be the permanent solution for my Add-ons, as the Core Team current view appears to be "Add-ons are just little unimportant toys which should do very very little". And maybe that's correct; maybe I have abused Add-ons to be "prototypes for core improvement" - e.g. advanced searching / backing up / copying of filters. It's just that not **all** of it's functionality would be beneficial to the majority of users._]

**Comment by jobisoft** [comment]
@realraven : Those two preferences are for testing, it really should not be used for production. You will not get that per extension, I asked.

Please also observe the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618860) I posted above. It looks like FF core will keep it as it is and i have word from Philipp, that he will not rule against the FF implementation. So storage.sync IS a really good candidate for permanent settings. We just have to wait.

`keepUuidOnUninstall ` will not generate a new UUID for each addons after remove/reinstall, which will allow the addons to access its old storage.

**Comment by opto** [comment]
John:
>A possible alternative solution is to automatically dump user data (via download API) 

does that truely work? From looking at code and current preferences, I had the impression that download without prompt uses the last download location, but that is global to TB.
So you would never know where you store to - the user could have changed it on the fly for another purpose.

Also: has anybody looked into how to get it back in? If I backup tags on emails, for example, the user can download the list. But how can TB (maybe even another TB on another PC) later read that in? It might work by the drag and drop api, but that feels ugly to force everybody to d'd.

**Comment by opto** [comment]
>Add-ons, as the Core Team current view appears to be "Add-ons are just little unimportant toys which should do very very little"

that would be ok if the missing functionality would be added to core. I can globally search over folders for emails, but there is no attachment column, so I cannot find the email with the contract attachment. That column is standard in all other messagelists.
All folder/messagelists have the possibility to display the highlighted message at the bottom - the search folderlist forgot to implement that.

The list of missing basic functions is long, and up to now, addons could help.

**Comment by jobisoft** [comment]
I am starting now with the second conversion step for EES: Preferences.

I will include a script/system, that
* allows to set defaults in background.js at "startup"
* has a convinient getPref() and setPref() function
* will auto-migrate prefs from legacy to storage.local (or storage.sync)

This is mostly done. What I need feedback upon is the options page itself. There are two main approaches out there. The first one originates from the old XUL preferences which supported something like this:

`<textbox id="to_address" preference="extensions.sendtocategory.to_address" />`

and the page loaded the values from the legacy backend automatically and also saved them automatically. The other approach is to do that manually and to have a JS script on the options page, that manually gets the pref values from the `nsIPrefService` and sets the value for each element and also updates the backend value onchange or onclose.

The first approach stopped working in TB68 but was brought back with the preferencesBindings.js from Firefox. We introduced that in our guide:
https://developer.thunderbird.net/add-ons/tb68/changes#less-than-prefwindow-greater-than-less-than-prefpane-greater-than-less-than-preferences-greater-than-and-less-than-preference-greater-than

This will stop working in TB74, as it uses the legacy pref system and the file preferencesBindings.js will probably have vanished as well.

EES is using the manual approach!
https://github.com/cleidigh/EditEmailSubject-MX/blob/v3.2/src/chrome/content/editemailsubjectSettings.xul

**Now the question: Should we mimic the behaviour of preferencesBindings.js (which is possible, but an additional resource consumer) and update EES in a way that it uses a preference tag? Or should we tell devs how to initialize html elements with values using our getPref() function during load and also how to use eventlisteners to store the new value upon changes or upon close?**
