### ISSUE TITLE
Edited info disappears

### ISSUE THREAD

**Issue by Jaylo70** [cleidigh/EditEmailSubject-MX#70]
I edit the information in the subject line but when I move the email to a folder, the information manually edited disappears and it's back to the original info.

**Comment by jobisoft** [comment]
This should only happen in "local" mode, which only modified the cache, not the file. See the add-on's options for disabling local mode (and changing the actual message, which will also change the message on the server, if the message is on an IMAP server).

But maybe we have to drop that functionality, because it causes so many confusions.

**Comment by Jaylo70** [comment]
OK thanks.  I did not know there was a option to change.

This is a great add-on.  The option should be automatically not checked and if people just want changes done to local emails they will check it.

**Comment by jobisoft** [comment]
I am working on an update for Thunderbird 115 and I will drop the option altogether.

**Comment by Jaylo70** [comment]
ok great thanks

**Comment by jobisoft** [comment]
Local mode has been removed:
https://github.com/cleidigh/EditEmailSubject-MX/commit/97d8950a39548b5735d5fb244f40c86da0906638

**Comment by jobisoft** [comment]
Please switch to v6.2, which introduced a backup option, to make sure no email is lost (there are such reports, v6.2 does fix something in that area)
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
