### ISSUE TITLE
Edited subjects undone when reparing the msf file

### ISSUE THREAD

**Issue by DGrothe-PhD** [cleidigh/EditEmailSubject-MX#71]
In Thunderbird, sometimes one needs to repair the msf file to fix some disrupted, mingled e-mail contents in a folder (picture shows a German dialog window to show what I am talking about)
![msf](https://user-images.githubusercontent.com/64636863/226454456-ab04d609-3b4c-4968-8981-6c29c7a67e1c.JPG)
I observe that repairing the msf file, the changes made to any e-mail subjects in that folder are made undone.

**Comment by jobisoft** [comment]
Does this happen only in "local" mode, or also in "imap" mode? I would assume, this only happens in "local" mode, because the msf file is the cache for the message database which we modify in local mode (In "imap" mode we change the message, and when the cache is cleared, it is rebuild fromt he message which also has the changed subject).

**Comment by DGrothe-PhD** [comment]
The folder shown above is one of my folders on the (IMAP) server. I can also confirm this happens in the inbox as well.

**Comment by jobisoft** [comment]
My question was not about your server being imap or pop, but if you had the local mode enabled in the EES options (which is default). I conclude this is the case. I purged support for the local mode for the next release, which will not fix this issue for you (because all messages which you have renamed were only renamed in the DB and not in the actual message), but it will prevent this from happening for mails renamed in the future.

For the time being, disable local mode.

**Comment by jobisoft** [comment]
Please switch to v6.2, which introduced a backup option, to make sure no email is lost (there are such reports, v6.2 does fix something in that area)
https://github.com/cleidigh/EditEmailSubject-MX/releases/tag/v6.2
